### ISSUE TITLE
Bug: can't programmatically use netlifyctl due to recent commit

### ISSUE THREAD

**Issue by greghuc** [netlify/netlifyctl#24]
Hi there,

This [recent commit](https://github.com/netlify/netlifyctl/commit/8cd353e91a142f5451a3b74be8547bf4828a8ba8) has busted my programmatic use of netlifyctl.

When I now run netlifyctl, I get:
```
[1] SOME-WEBSITE-prod
[2] SOME-WEBSITE-staging
=> Which site?
```

This is a bug, as netlifyctl already knows which website I'm deploying: I specify the appropriate website api id in the supplied config file.

The "Which site?" option means that programmatic use of netlifyctl is now busted. Everything worked until I pulled in this commit.

**Comment by rybit** [comment]
Hmm - that is odd. That should only be triggered if you don't have a site configured in the .toml file. I will take a look a little later this afternoon.

For the moment you can use the pinned version if it is blocking you.

**Comment by greghuc** [comment]
Thanks - I've switched to the latest binary release, and things work fine.

**Comment by calavera** [comment]
@rybit I think the problem is that you can get into the choosing logic when you already have an id:

The `else` statement in https://github.com/netlify/netlifyctl/pull/23/files#diff-ed4163555fbb594960579ba8897c6f1fR60 should probably be a `if conf.Settings.ID == ""` to only get into that logic if there is no ID
